# Generated by Django 5.2 on 2025-05-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0003_rename_bookingdate_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inventory', models.SmallIntegerField()),
            ],
        ),
    ]
